import React from 'react';

interface CognitiveProfileDisplayProps {
  analysisText: string;
  provider: string;
}

const CognitiveProfileDisplay: React.FC<CognitiveProfileDisplayProps> = ({
  analysisText,
  provider
}) => {
  return (
    <div className="mt-6 mb-10">
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-semibold text-gray-800">Cognitive Profile Analysis</h2>
          <div className="text-sm bg-blue-100 text-blue-800 px-3 py-1 rounded-full">
            {provider}
          </div>
        </div>
        
        <div className="prose prose-lg max-w-none whitespace-pre-wrap font-serif">
          {analysisText}
        </div>
        
        <div className="mt-6 pt-4 border-t border-gray-200">
          <p className="text-sm text-gray-500">
            This is a pure pass-through cognitive profile generated by analyzing the text as forensic evidence.
            The intelligence score and profile are produced directly by the AI without any internal scoring logic.
          </p>
        </div>
      </div>
    </div>
  );
};

export default CognitiveProfileDisplay;